[versions]
agp = "9.0.1"
kotlin = "2.3.10"
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
sentry = "8.33.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
sentry-android = { group = "io.sentry", name = "sentry-android", version.ref = "sentry" }
sentry-android-replay = { group = "io.sentry", name = "sentry-android-replay", version.ref = "sentry" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
