rootProject.name = "moneat-backend"

include(":feature-spi")
include(":ingest-common")
include(":features:ai")
include(":features:analytics")
include(":features:billing")
include(":features:contact")
include(":features:dashboards")
include(":features:datadog")
include(":features:featureflags")
include(":features:incident")
include(":features:llm")
include(":features:logs")
include(":features:mcp")
include(":features:monitoring")
include(":features:otlp")
include(":features:overview")
include(":features:sso")
include(":features:statuspage")
include(":features:summary")
include(":features:uptime")

// Enterprise modules (SSO, On-Call) — lives in ee/backend/ within the monorepo
include(":ee")
project(":ee").projectDir = file("../ee/backend")
