/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReplaysRouteImport } from './routes/replays'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerformanceIndexRouteImport } from './routes/performance.index'
import { Route as MonitoringIndexRouteImport } from './routes/monitoring.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ReplaysReplayIdRouteImport } from './routes/replays.$replayId'
import { Route as ReleasesVersionRouteImport } from './routes/releases.$version'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as PerformanceTransactionIdRouteImport } from './routes/performance.$transactionId'
import { Route as MonitoringSystemIdRouteImport } from './routes/monitoring.$systemId'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as IssuesIssueIdRouteImport } from './routes/issues.$issueId'
import { Route as FeedbackFeedbackIdRouteImport } from './routes/feedback.$feedbackId'
import { Route as AdminUsageRouteImport } from './routes/admin.usage'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminOrganizationsRouteImport } from './routes/admin.organizations'
import { Route as AdminInfrastructureRouteImport } from './routes/admin.infrastructure'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects.$projectId.settings'
import { Route as AdminOrganizationsOrgIdRouteImport } from './routes/admin.organizations.$orgId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplaysRoute = ReplaysRouteImport.update({
  id: '/replays',
  path: '/replays',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceIndexRoute = PerformanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PerformanceRoute,
} as any)
const MonitoringIndexRoute = MonitoringIndexRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ReplaysReplayIdRoute = ReplaysReplayIdRouteImport.update({
  id: '/$replayId',
  path: '/$replayId',
  getParentRoute: () => ReplaysRoute,
} as any)
const ReleasesVersionRoute = ReleasesVersionRouteImport.update({
  id: '/$version',
  path: '/$version',
  getParentRoute: () => ReleasesRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const PerformanceTransactionIdRoute =
  PerformanceTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => PerformanceRoute,
  } as any)
const MonitoringSystemIdRoute = MonitoringSystemIdRouteImport.update({
  id: '/monitoring/$systemId',
  path: '/monitoring/$systemId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIssueIdRoute = IssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackFeedbackIdRoute = FeedbackFeedbackIdRouteImport.update({
  id: '/$feedbackId',
  path: '/$feedbackId',
  getParentRoute: () => FeedbackRoute,
} as any)
const AdminUsageRoute = AdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfrastructureRoute = AdminInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const AdminOrganizationsOrgIdRoute = AdminOrganizationsOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => AdminOrganizationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/feedback': typeof FeedbackRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/performance': typeof PerformanceRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/releases': typeof ReleasesRouteWithChildren
  '/replays': typeof ReplaysRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/organizations': typeof AdminOrganizationsRouteWithChildren
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/usage': typeof AdminUsageRoute
  '/feedback/$feedbackId': typeof FeedbackFeedbackIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/monitoring/$systemId': typeof MonitoringSystemIdRoute
  '/performance/$transactionId': typeof PerformanceTransactionIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/releases/$version': typeof ReleasesVersionRoute
  '/replays/$replayId': typeof ReplaysReplayIdRoute
  '/admin/': typeof AdminIndexRoute
  '/monitoring/': typeof MonitoringIndexRoute
  '/performance/': typeof PerformanceIndexRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/feedback': typeof FeedbackRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/releases': typeof ReleasesRouteWithChildren
  '/replays': typeof ReplaysRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/organizations': typeof AdminOrganizationsRouteWithChildren
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/usage': typeof AdminUsageRoute
  '/feedback/$feedbackId': typeof FeedbackFeedbackIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/monitoring/$systemId': typeof MonitoringSystemIdRoute
  '/performance/$transactionId': typeof PerformanceTransactionIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/releases/$version': typeof ReleasesVersionRoute
  '/replays/$replayId': typeof ReplaysReplayIdRoute
  '/admin': typeof AdminIndexRoute
  '/monitoring': typeof MonitoringIndexRoute
  '/performance': typeof PerformanceIndexRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/feedback': typeof FeedbackRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/performance': typeof PerformanceRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/releases': typeof ReleasesRouteWithChildren
  '/replays': typeof ReplaysRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/organizations': typeof AdminOrganizationsRouteWithChildren
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/usage': typeof AdminUsageRoute
  '/feedback/$feedbackId': typeof FeedbackFeedbackIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/monitoring/$systemId': typeof MonitoringSystemIdRoute
  '/performance/$transactionId': typeof PerformanceTransactionIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/releases/$version': typeof ReleasesVersionRoute
  '/replays/$replayId': typeof ReplaysReplayIdRoute
  '/admin/': typeof AdminIndexRoute
  '/monitoring/': typeof MonitoringIndexRoute
  '/performance/': typeof PerformanceIndexRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/feedback'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/performance'
    | '/privacy'
    | '/projects'
    | '/releases'
    | '/replays'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/billing'
    | '/admin/emails'
    | '/admin/infrastructure'
    | '/admin/organizations'
    | '/admin/revenue'
    | '/admin/usage'
    | '/feedback/$feedbackId'
    | '/issues/$issueId'
    | '/legal/privacy'
    | '/legal/terms'
    | '/monitoring/$systemId'
    | '/performance/$transactionId'
    | '/projects/$projectId'
    | '/releases/$version'
    | '/replays/$replayId'
    | '/admin/'
    | '/monitoring/'
    | '/performance/'
    | '/admin/organizations/$orgId'
    | '/projects/$projectId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/feedback'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/projects'
    | '/releases'
    | '/replays'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/billing'
    | '/admin/emails'
    | '/admin/infrastructure'
    | '/admin/organizations'
    | '/admin/revenue'
    | '/admin/usage'
    | '/feedback/$feedbackId'
    | '/issues/$issueId'
    | '/legal/privacy'
    | '/legal/terms'
    | '/monitoring/$systemId'
    | '/performance/$transactionId'
    | '/projects/$projectId'
    | '/releases/$version'
    | '/replays/$replayId'
    | '/admin'
    | '/monitoring'
    | '/performance'
    | '/admin/organizations/$orgId'
    | '/projects/$projectId/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/feedback'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/performance'
    | '/privacy'
    | '/projects'
    | '/releases'
    | '/replays'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/billing'
    | '/admin/emails'
    | '/admin/infrastructure'
    | '/admin/organizations'
    | '/admin/revenue'
    | '/admin/usage'
    | '/feedback/$feedbackId'
    | '/issues/$issueId'
    | '/legal/privacy'
    | '/legal/terms'
    | '/monitoring/$systemId'
    | '/performance/$transactionId'
    | '/projects/$projectId'
    | '/releases/$version'
    | '/replays/$replayId'
    | '/admin/'
    | '/monitoring/'
    | '/performance/'
    | '/admin/organizations/$orgId'
    | '/projects/$projectId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  FeedbackRoute: typeof FeedbackRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PerformanceRoute: typeof PerformanceRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReleasesRoute: typeof ReleasesRouteWithChildren
  ReplaysRoute: typeof ReplaysRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  IssuesIssueIdRoute: typeof IssuesIssueIdRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  MonitoringSystemIdRoute: typeof MonitoringSystemIdRoute
  MonitoringIndexRoute: typeof MonitoringIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replays': {
      id: '/replays'
      path: '/replays'
      fullPath: '/replays'
      preLoaderRoute: typeof ReplaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance/': {
      id: '/performance/'
      path: '/'
      fullPath: '/performance/'
      preLoaderRoute: typeof PerformanceIndexRouteImport
      parentRoute: typeof PerformanceRoute
    }
    '/monitoring/': {
      id: '/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof MonitoringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/replays/$replayId': {
      id: '/replays/$replayId'
      path: '/$replayId'
      fullPath: '/replays/$replayId'
      preLoaderRoute: typeof ReplaysReplayIdRouteImport
      parentRoute: typeof ReplaysRoute
    }
    '/releases/$version': {
      id: '/releases/$version'
      path: '/$version'
      fullPath: '/releases/$version'
      preLoaderRoute: typeof ReleasesVersionRouteImport
      parentRoute: typeof ReleasesRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/performance/$transactionId': {
      id: '/performance/$transactionId'
      path: '/$transactionId'
      fullPath: '/performance/$transactionId'
      preLoaderRoute: typeof PerformanceTransactionIdRouteImport
      parentRoute: typeof PerformanceRoute
    }
    '/monitoring/$systemId': {
      id: '/monitoring/$systemId'
      path: '/monitoring/$systemId'
      fullPath: '/monitoring/$systemId'
      preLoaderRoute: typeof MonitoringSystemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$issueId': {
      id: '/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof IssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$feedbackId': {
      id: '/feedback/$feedbackId'
      path: '/$feedbackId'
      fullPath: '/feedback/$feedbackId'
      preLoaderRoute: typeof FeedbackFeedbackIdRouteImport
      parentRoute: typeof FeedbackRoute
    }
    '/admin/usage': {
      id: '/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AdminUsageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/infrastructure': {
      id: '/admin/infrastructure'
      path: '/infrastructure'
      fullPath: '/admin/infrastructure'
      preLoaderRoute: typeof AdminInfrastructureRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/admin/organizations/$orgId': {
      id: '/admin/organizations/$orgId'
      path: '/$orgId'
      fullPath: '/admin/organizations/$orgId'
      preLoaderRoute: typeof AdminOrganizationsOrgIdRouteImport
      parentRoute: typeof AdminOrganizationsRoute
    }
  }
}

interface AdminOrganizationsRouteChildren {
  AdminOrganizationsOrgIdRoute: typeof AdminOrganizationsOrgIdRoute
}

const AdminOrganizationsRouteChildren: AdminOrganizationsRouteChildren = {
  AdminOrganizationsOrgIdRoute: AdminOrganizationsOrgIdRoute,
}

const AdminOrganizationsRouteWithChildren =
  AdminOrganizationsRoute._addFileChildren(AdminOrganizationsRouteChildren)

interface AdminRouteChildren {
  AdminBillingRoute: typeof AdminBillingRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminInfrastructureRoute: typeof AdminInfrastructureRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRouteWithChildren
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminUsageRoute: typeof AdminUsageRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBillingRoute: AdminBillingRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminInfrastructureRoute: AdminInfrastructureRoute,
  AdminOrganizationsRoute: AdminOrganizationsRouteWithChildren,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminUsageRoute: AdminUsageRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FeedbackRouteChildren {
  FeedbackFeedbackIdRoute: typeof FeedbackFeedbackIdRoute
}

const FeedbackRouteChildren: FeedbackRouteChildren = {
  FeedbackFeedbackIdRoute: FeedbackFeedbackIdRoute,
}

const FeedbackRouteWithChildren = FeedbackRoute._addFileChildren(
  FeedbackRouteChildren,
)

interface PerformanceRouteChildren {
  PerformanceTransactionIdRoute: typeof PerformanceTransactionIdRoute
  PerformanceIndexRoute: typeof PerformanceIndexRoute
}

const PerformanceRouteChildren: PerformanceRouteChildren = {
  PerformanceTransactionIdRoute: PerformanceTransactionIdRoute,
  PerformanceIndexRoute: PerformanceIndexRoute,
}

const PerformanceRouteWithChildren = PerformanceRoute._addFileChildren(
  PerformanceRouteChildren,
)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ReleasesRouteChildren {
  ReleasesVersionRoute: typeof ReleasesVersionRoute
}

const ReleasesRouteChildren: ReleasesRouteChildren = {
  ReleasesVersionRoute: ReleasesVersionRoute,
}

const ReleasesRouteWithChildren = ReleasesRoute._addFileChildren(
  ReleasesRouteChildren,
)

interface ReplaysRouteChildren {
  ReplaysReplayIdRoute: typeof ReplaysReplayIdRoute
}

const ReplaysRouteChildren: ReplaysRouteChildren = {
  ReplaysReplayIdRoute: ReplaysReplayIdRoute,
}

const ReplaysRouteWithChildren =
  ReplaysRoute._addFileChildren(ReplaysRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  FeedbackRoute: FeedbackRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PerformanceRoute: PerformanceRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReleasesRoute: ReleasesRouteWithChildren,
  ReplaysRoute: ReplaysRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  IssuesIssueIdRoute: IssuesIssueIdRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  MonitoringSystemIdRoute: MonitoringSystemIdRoute,
  MonitoringIndexRoute: MonitoringIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
