/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReplaysRouteImport } from './routes/replays'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerformanceIndexRouteImport } from './routes/performance.index'
import { Route as ReplaysReplayIdRouteImport } from './routes/replays.$replayId'
import { Route as ReleasesVersionRouteImport } from './routes/releases.$version'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as PerformanceTransactionIdRouteImport } from './routes/performance.$transactionId'
import { Route as IssuesIssueIdRouteImport } from './routes/issues.$issueId'
import { Route as FeedbackFeedbackIdRouteImport } from './routes/feedback.$feedbackId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplaysRoute = ReplaysRouteImport.update({
  id: '/replays',
  path: '/replays',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceIndexRoute = PerformanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PerformanceRoute,
} as any)
const ReplaysReplayIdRoute = ReplaysReplayIdRouteImport.update({
  id: '/$replayId',
  path: '/$replayId',
  getParentRoute: () => ReplaysRoute,
} as any)
const ReleasesVersionRoute = ReleasesVersionRouteImport.update({
  id: '/$version',
  path: '/$version',
  getParentRoute: () => ReleasesRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const PerformanceTransactionIdRoute =
  PerformanceTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => PerformanceRoute,
  } as any)
const IssuesIssueIdRoute = IssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackFeedbackIdRoute = FeedbackFeedbackIdRouteImport.update({
  id: '/$feedbackId',
  path: '/$feedbackId',
  getParentRoute: () => FeedbackRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/feedback': typeof FeedbackRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/performance': typeof PerformanceRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/releases': typeof ReleasesRouteWithChildren
  '/replays': typeof ReplaysRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/feedback/$feedbackId': typeof FeedbackFeedbackIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/performance/$transactionId': typeof PerformanceTransactionIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/releases/$version': typeof ReleasesVersionRoute
  '/replays/$replayId': typeof ReplaysReplayIdRoute
  '/performance/': typeof PerformanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/feedback': typeof FeedbackRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/releases': typeof ReleasesRouteWithChildren
  '/replays': typeof ReplaysRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/feedback/$feedbackId': typeof FeedbackFeedbackIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/performance/$transactionId': typeof PerformanceTransactionIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/releases/$version': typeof ReleasesVersionRoute
  '/replays/$replayId': typeof ReplaysReplayIdRoute
  '/performance': typeof PerformanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/feedback': typeof FeedbackRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/performance': typeof PerformanceRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/releases': typeof ReleasesRouteWithChildren
  '/replays': typeof ReplaysRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/feedback/$feedbackId': typeof FeedbackFeedbackIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/performance/$transactionId': typeof PerformanceTransactionIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/releases/$version': typeof ReleasesVersionRoute
  '/replays/$replayId': typeof ReplaysReplayIdRoute
  '/performance/': typeof PerformanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/feedback'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/performance'
    | '/projects'
    | '/releases'
    | '/replays'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/feedback/$feedbackId'
    | '/issues/$issueId'
    | '/performance/$transactionId'
    | '/projects/$projectId'
    | '/releases/$version'
    | '/replays/$replayId'
    | '/performance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/feedback'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/projects'
    | '/releases'
    | '/replays'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/feedback/$feedbackId'
    | '/issues/$issueId'
    | '/performance/$transactionId'
    | '/projects/$projectId'
    | '/releases/$version'
    | '/replays/$replayId'
    | '/performance'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/feedback'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/performance'
    | '/projects'
    | '/releases'
    | '/replays'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/verify-email'
    | '/feedback/$feedbackId'
    | '/issues/$issueId'
    | '/performance/$transactionId'
    | '/projects/$projectId'
    | '/releases/$version'
    | '/replays/$replayId'
    | '/performance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  FeedbackRoute: typeof FeedbackRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PerformanceRoute: typeof PerformanceRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReleasesRoute: typeof ReleasesRouteWithChildren
  ReplaysRoute: typeof ReplaysRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  IssuesIssueIdRoute: typeof IssuesIssueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replays': {
      id: '/replays'
      path: '/replays'
      fullPath: '/replays'
      preLoaderRoute: typeof ReplaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance/': {
      id: '/performance/'
      path: '/'
      fullPath: '/performance/'
      preLoaderRoute: typeof PerformanceIndexRouteImport
      parentRoute: typeof PerformanceRoute
    }
    '/replays/$replayId': {
      id: '/replays/$replayId'
      path: '/$replayId'
      fullPath: '/replays/$replayId'
      preLoaderRoute: typeof ReplaysReplayIdRouteImport
      parentRoute: typeof ReplaysRoute
    }
    '/releases/$version': {
      id: '/releases/$version'
      path: '/$version'
      fullPath: '/releases/$version'
      preLoaderRoute: typeof ReleasesVersionRouteImport
      parentRoute: typeof ReleasesRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/performance/$transactionId': {
      id: '/performance/$transactionId'
      path: '/$transactionId'
      fullPath: '/performance/$transactionId'
      preLoaderRoute: typeof PerformanceTransactionIdRouteImport
      parentRoute: typeof PerformanceRoute
    }
    '/issues/$issueId': {
      id: '/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof IssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$feedbackId': {
      id: '/feedback/$feedbackId'
      path: '/$feedbackId'
      fullPath: '/feedback/$feedbackId'
      preLoaderRoute: typeof FeedbackFeedbackIdRouteImport
      parentRoute: typeof FeedbackRoute
    }
  }
}

interface FeedbackRouteChildren {
  FeedbackFeedbackIdRoute: typeof FeedbackFeedbackIdRoute
}

const FeedbackRouteChildren: FeedbackRouteChildren = {
  FeedbackFeedbackIdRoute: FeedbackFeedbackIdRoute,
}

const FeedbackRouteWithChildren = FeedbackRoute._addFileChildren(
  FeedbackRouteChildren,
)

interface PerformanceRouteChildren {
  PerformanceTransactionIdRoute: typeof PerformanceTransactionIdRoute
  PerformanceIndexRoute: typeof PerformanceIndexRoute
}

const PerformanceRouteChildren: PerformanceRouteChildren = {
  PerformanceTransactionIdRoute: PerformanceTransactionIdRoute,
  PerformanceIndexRoute: PerformanceIndexRoute,
}

const PerformanceRouteWithChildren = PerformanceRoute._addFileChildren(
  PerformanceRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ReleasesRouteChildren {
  ReleasesVersionRoute: typeof ReleasesVersionRoute
}

const ReleasesRouteChildren: ReleasesRouteChildren = {
  ReleasesVersionRoute: ReleasesVersionRoute,
}

const ReleasesRouteWithChildren = ReleasesRoute._addFileChildren(
  ReleasesRouteChildren,
)

interface ReplaysRouteChildren {
  ReplaysReplayIdRoute: typeof ReplaysReplayIdRoute
}

const ReplaysRouteChildren: ReplaysRouteChildren = {
  ReplaysReplayIdRoute: ReplaysReplayIdRoute,
}

const ReplaysRouteWithChildren =
  ReplaysRoute._addFileChildren(ReplaysRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  FeedbackRoute: FeedbackRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PerformanceRoute: PerformanceRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReleasesRoute: ReleasesRouteWithChildren,
  ReplaysRoute: ReplaysRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  IssuesIssueIdRoute: IssuesIssueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
