-- Seed new tier config versions with unified ingestion billing model.
-- All DD Agent features enabled on all tiers. Per-type count limits set to
-- Long.MAX_VALUE (effectively disabled) as GB is now the primary gate.

-- Mark existing versions as non-current
UPDATE pricing_tier_configs SET is_current = false WHERE is_current = true;

-- FREE tier: 1 GB ingestion, 100K custom metrics, 3 hosts, all features
INSERT INTO pricing_tier_configs (
    tier_name, version, monthly_unit_limit,
    monthly_error_limit, monthly_transaction_limit, monthly_replay_limit,
    monthly_feedback_limit, monthly_llm_event_limit,
    monthly_gb_limit, retention_days, log_retention_days,
    replay_retention_days, llm_retention_days,
    status_pages_enabled, status_page_custom_domain_enabled,
    session_replay_enabled, slack_enabled, discord_enabled,
    incident_io_enabled, saml_enabled, oidc_enabled,
    priority_support_enabled, sla_enabled, custom_retention_enabled,
    max_projects, max_systems, monitor_interval_seconds,
    monthly_price_cents, yearly_price_cents, trial_days,
    payg_enabled, payg_rate_micros_per_unit,
    overage_rate_cents_per_gb,
    error_overage_rate_cents_per_1k, replay_overage_rate_cents_per_gb,
    llm_overage_rate_cents_per_1k,
    oncall_per_user_monthly_cents, oncall_per_user_yearly_cents, oncall_enabled,
    max_analytics_sites, analytics_retention_days,
    monthly_analytics_pageview_limit, analytics_pageview_overage_rate_cents_per_100k,
    monthly_apm_span_limit, apm_span_overage_rate_cents_per_1m,
    monthly_custom_metric_limit, custom_metric_overage_rate_cents_per_100k,
    max_hosts, profiling_enabled, network_monitoring_enabled,
    dbm_enabled, debugger_enabled, k8s_monitoring_enabled,
    data_streams_enabled, sbom_enabled, synthetics_enabled,
    is_current, created_at
) VALUES (
    'FREE', 3, 9223372036854775807,
    9223372036854775807, 9223372036854775807, 9223372036854775807,
    9223372036854775807, 9223372036854775807,
    1073741824, 3, 3,
    3, 3,
    true, true,
    true, true, true,
    false, false, false,
    false, false, false,
    1, 3, 60,
    0, 0, 0,
    false, 0,
    0,
    0, 0,
    0,
    0, 0, false,
    1, 1095,
    10000, 0,
    9223372036854775807, 0,
    100000, 0,
    3, true, true,
    true, true, true,
    true, true, true,
    true, NOW()
) ON CONFLICT (tier_name, version) DO UPDATE SET
    monthly_unit_limit = EXCLUDED.monthly_unit_limit,
    monthly_error_limit = EXCLUDED.monthly_error_limit,
    monthly_transaction_limit = EXCLUDED.monthly_transaction_limit,
    monthly_replay_limit = EXCLUDED.monthly_replay_limit,
    monthly_feedback_limit = EXCLUDED.monthly_feedback_limit,
    monthly_llm_event_limit = EXCLUDED.monthly_llm_event_limit,
    monthly_gb_limit = EXCLUDED.monthly_gb_limit,
    retention_days = EXCLUDED.retention_days,
    log_retention_days = EXCLUDED.log_retention_days,
    replay_retention_days = EXCLUDED.replay_retention_days,
    llm_retention_days = EXCLUDED.llm_retention_days,
    status_pages_enabled = EXCLUDED.status_pages_enabled,
    status_page_custom_domain_enabled = EXCLUDED.status_page_custom_domain_enabled,
    session_replay_enabled = EXCLUDED.session_replay_enabled,
    slack_enabled = EXCLUDED.slack_enabled,
    discord_enabled = EXCLUDED.discord_enabled,
    incident_io_enabled = EXCLUDED.incident_io_enabled,
    saml_enabled = EXCLUDED.saml_enabled,
    oidc_enabled = EXCLUDED.oidc_enabled,
    priority_support_enabled = EXCLUDED.priority_support_enabled,
    sla_enabled = EXCLUDED.sla_enabled,
    custom_retention_enabled = EXCLUDED.custom_retention_enabled,
    max_projects = EXCLUDED.max_projects,
    max_systems = EXCLUDED.max_systems,
    monitor_interval_seconds = EXCLUDED.monitor_interval_seconds,
    monthly_price_cents = EXCLUDED.monthly_price_cents,
    yearly_price_cents = EXCLUDED.yearly_price_cents,
    trial_days = EXCLUDED.trial_days,
    payg_enabled = EXCLUDED.payg_enabled,
    payg_rate_micros_per_unit = EXCLUDED.payg_rate_micros_per_unit,
    overage_rate_cents_per_gb = EXCLUDED.overage_rate_cents_per_gb,
    error_overage_rate_cents_per_1k = EXCLUDED.error_overage_rate_cents_per_1k,
    replay_overage_rate_cents_per_gb = EXCLUDED.replay_overage_rate_cents_per_gb,
    llm_overage_rate_cents_per_1k = EXCLUDED.llm_overage_rate_cents_per_1k,
    oncall_per_user_monthly_cents = EXCLUDED.oncall_per_user_monthly_cents,
    oncall_per_user_yearly_cents = EXCLUDED.oncall_per_user_yearly_cents,
    oncall_enabled = EXCLUDED.oncall_enabled,
    max_analytics_sites = EXCLUDED.max_analytics_sites,
    analytics_retention_days = EXCLUDED.analytics_retention_days,
    monthly_analytics_pageview_limit = EXCLUDED.monthly_analytics_pageview_limit,
    analytics_pageview_overage_rate_cents_per_100k = EXCLUDED.analytics_pageview_overage_rate_cents_per_100k,
    monthly_apm_span_limit = EXCLUDED.monthly_apm_span_limit,
    apm_span_overage_rate_cents_per_1m = EXCLUDED.apm_span_overage_rate_cents_per_1m,
    monthly_custom_metric_limit = EXCLUDED.monthly_custom_metric_limit,
    custom_metric_overage_rate_cents_per_100k = EXCLUDED.custom_metric_overage_rate_cents_per_100k,
    max_hosts = EXCLUDED.max_hosts,
    profiling_enabled = EXCLUDED.profiling_enabled,
    network_monitoring_enabled = EXCLUDED.network_monitoring_enabled,
    dbm_enabled = EXCLUDED.dbm_enabled,
    debugger_enabled = EXCLUDED.debugger_enabled,
    k8s_monitoring_enabled = EXCLUDED.k8s_monitoring_enabled,
    data_streams_enabled = EXCLUDED.data_streams_enabled,
    sbom_enabled = EXCLUDED.sbom_enabled,
    synthetics_enabled = EXCLUDED.synthetics_enabled,
    is_current = EXCLUDED.is_current;

-- PRO tier: 50 GB ingestion, 1M custom metrics, unlimited hosts
INSERT INTO pricing_tier_configs (
    tier_name, version, monthly_unit_limit,
    monthly_error_limit, monthly_transaction_limit, monthly_replay_limit,
    monthly_feedback_limit, monthly_llm_event_limit,
    monthly_gb_limit, retention_days, log_retention_days,
    replay_retention_days, llm_retention_days,
    status_pages_enabled, status_page_custom_domain_enabled,
    session_replay_enabled, slack_enabled, discord_enabled,
    incident_io_enabled, saml_enabled, oidc_enabled,
    priority_support_enabled, sla_enabled, custom_retention_enabled,
    max_projects, max_systems, monitor_interval_seconds,
    monthly_price_cents, yearly_price_cents, trial_days,
    payg_enabled, payg_rate_micros_per_unit,
    overage_rate_cents_per_gb,
    error_overage_rate_cents_per_1k, replay_overage_rate_cents_per_gb,
    llm_overage_rate_cents_per_1k,
    oncall_per_user_monthly_cents, oncall_per_user_yearly_cents, oncall_enabled,
    max_analytics_sites, analytics_retention_days,
    monthly_analytics_pageview_limit, analytics_pageview_overage_rate_cents_per_100k,
    monthly_apm_span_limit, apm_span_overage_rate_cents_per_1m,
    monthly_custom_metric_limit, custom_metric_overage_rate_cents_per_100k,
    max_hosts, profiling_enabled, network_monitoring_enabled,
    dbm_enabled, debugger_enabled, k8s_monitoring_enabled,
    data_streams_enabled, sbom_enabled, synthetics_enabled,
    is_current, created_at
) VALUES (
    'PRO', 3, 9223372036854775807,
    9223372036854775807, 9223372036854775807, 9223372036854775807,
    9223372036854775807, 9223372036854775807,
    53687091200, 30, 30,
    30, 30,
    true, true,
    true, true, true,
    false, false, false,
    false, false, false,
    NULL, 10, 30,
    2900, 28800, 14,
    true, 400000,
    40,
    0, 0,
    0,
    500, 5000, true,
    5, 1095,
    100000, 1000,
    9223372036854775807, 0,
    1000000, 50,
    NULL, true, true,
    true, true, true,
    true, true, true,
    true, NOW()
) ON CONFLICT (tier_name, version) DO UPDATE SET
    monthly_unit_limit = EXCLUDED.monthly_unit_limit,
    monthly_error_limit = EXCLUDED.monthly_error_limit,
    monthly_transaction_limit = EXCLUDED.monthly_transaction_limit,
    monthly_replay_limit = EXCLUDED.monthly_replay_limit,
    monthly_feedback_limit = EXCLUDED.monthly_feedback_limit,
    monthly_llm_event_limit = EXCLUDED.monthly_llm_event_limit,
    monthly_gb_limit = EXCLUDED.monthly_gb_limit,
    retention_days = EXCLUDED.retention_days,
    log_retention_days = EXCLUDED.log_retention_days,
    replay_retention_days = EXCLUDED.replay_retention_days,
    llm_retention_days = EXCLUDED.llm_retention_days,
    status_pages_enabled = EXCLUDED.status_pages_enabled,
    status_page_custom_domain_enabled = EXCLUDED.status_page_custom_domain_enabled,
    session_replay_enabled = EXCLUDED.session_replay_enabled,
    slack_enabled = EXCLUDED.slack_enabled,
    discord_enabled = EXCLUDED.discord_enabled,
    incident_io_enabled = EXCLUDED.incident_io_enabled,
    saml_enabled = EXCLUDED.saml_enabled,
    oidc_enabled = EXCLUDED.oidc_enabled,
    priority_support_enabled = EXCLUDED.priority_support_enabled,
    sla_enabled = EXCLUDED.sla_enabled,
    custom_retention_enabled = EXCLUDED.custom_retention_enabled,
    max_projects = EXCLUDED.max_projects,
    max_systems = EXCLUDED.max_systems,
    monitor_interval_seconds = EXCLUDED.monitor_interval_seconds,
    monthly_price_cents = EXCLUDED.monthly_price_cents,
    yearly_price_cents = EXCLUDED.yearly_price_cents,
    trial_days = EXCLUDED.trial_days,
    payg_enabled = EXCLUDED.payg_enabled,
    payg_rate_micros_per_unit = EXCLUDED.payg_rate_micros_per_unit,
    overage_rate_cents_per_gb = EXCLUDED.overage_rate_cents_per_gb,
    error_overage_rate_cents_per_1k = EXCLUDED.error_overage_rate_cents_per_1k,
    replay_overage_rate_cents_per_gb = EXCLUDED.replay_overage_rate_cents_per_gb,
    llm_overage_rate_cents_per_1k = EXCLUDED.llm_overage_rate_cents_per_1k,
    oncall_per_user_monthly_cents = EXCLUDED.oncall_per_user_monthly_cents,
    oncall_per_user_yearly_cents = EXCLUDED.oncall_per_user_yearly_cents,
    oncall_enabled = EXCLUDED.oncall_enabled,
    max_analytics_sites = EXCLUDED.max_analytics_sites,
    analytics_retention_days = EXCLUDED.analytics_retention_days,
    monthly_analytics_pageview_limit = EXCLUDED.monthly_analytics_pageview_limit,
    analytics_pageview_overage_rate_cents_per_100k = EXCLUDED.analytics_pageview_overage_rate_cents_per_100k,
    monthly_apm_span_limit = EXCLUDED.monthly_apm_span_limit,
    apm_span_overage_rate_cents_per_1m = EXCLUDED.apm_span_overage_rate_cents_per_1m,
    monthly_custom_metric_limit = EXCLUDED.monthly_custom_metric_limit,
    custom_metric_overage_rate_cents_per_100k = EXCLUDED.custom_metric_overage_rate_cents_per_100k,
    max_hosts = EXCLUDED.max_hosts,
    profiling_enabled = EXCLUDED.profiling_enabled,
    network_monitoring_enabled = EXCLUDED.network_monitoring_enabled,
    dbm_enabled = EXCLUDED.dbm_enabled,
    debugger_enabled = EXCLUDED.debugger_enabled,
    k8s_monitoring_enabled = EXCLUDED.k8s_monitoring_enabled,
    data_streams_enabled = EXCLUDED.data_streams_enabled,
    sbom_enabled = EXCLUDED.sbom_enabled,
    synthetics_enabled = EXCLUDED.synthetics_enabled,
    is_current = EXCLUDED.is_current;

-- TEAM tier: 200 GB ingestion, 10M custom metrics, unlimited hosts
INSERT INTO pricing_tier_configs (
    tier_name, version, monthly_unit_limit,
    monthly_error_limit, monthly_transaction_limit, monthly_replay_limit,
    monthly_feedback_limit, monthly_llm_event_limit,
    monthly_gb_limit, retention_days, log_retention_days,
    replay_retention_days, llm_retention_days,
    status_pages_enabled, status_page_custom_domain_enabled,
    session_replay_enabled, slack_enabled, discord_enabled,
    incident_io_enabled, saml_enabled, oidc_enabled,
    priority_support_enabled, sla_enabled, custom_retention_enabled,
    max_projects, max_systems, monitor_interval_seconds,
    monthly_price_cents, yearly_price_cents, trial_days,
    payg_enabled, payg_rate_micros_per_unit,
    overage_rate_cents_per_gb,
    error_overage_rate_cents_per_1k, replay_overage_rate_cents_per_gb,
    llm_overage_rate_cents_per_1k,
    oncall_per_user_monthly_cents, oncall_per_user_yearly_cents, oncall_enabled,
    max_analytics_sites, analytics_retention_days,
    monthly_analytics_pageview_limit, analytics_pageview_overage_rate_cents_per_100k,
    monthly_apm_span_limit, apm_span_overage_rate_cents_per_1m,
    monthly_custom_metric_limit, custom_metric_overage_rate_cents_per_100k,
    max_hosts, profiling_enabled, network_monitoring_enabled,
    dbm_enabled, debugger_enabled, k8s_monitoring_enabled,
    data_streams_enabled, sbom_enabled, synthetics_enabled,
    is_current, created_at
) VALUES (
    'TEAM', 3, 9223372036854775807,
    9223372036854775807, 9223372036854775807, 9223372036854775807,
    9223372036854775807, 9223372036854775807,
    214748364800, 30, 30,
    30, 30,
    true, true,
    true, true, true,
    true, true, true,
    false, false, false,
    NULL, 25, 10,
    7900, 79200, 14,
    true, 400000,
    40,
    0, 0,
    0,
    500, 5000, true,
    10, 1825,
    1000000, 1000,
    9223372036854775807, 0,
    10000000, 50,
    NULL, true, true,
    true, true, true,
    true, true, true,
    true, NOW()
) ON CONFLICT (tier_name, version) DO UPDATE SET
    monthly_unit_limit = EXCLUDED.monthly_unit_limit,
    monthly_error_limit = EXCLUDED.monthly_error_limit,
    monthly_transaction_limit = EXCLUDED.monthly_transaction_limit,
    monthly_replay_limit = EXCLUDED.monthly_replay_limit,
    monthly_feedback_limit = EXCLUDED.monthly_feedback_limit,
    monthly_llm_event_limit = EXCLUDED.monthly_llm_event_limit,
    monthly_gb_limit = EXCLUDED.monthly_gb_limit,
    retention_days = EXCLUDED.retention_days,
    log_retention_days = EXCLUDED.log_retention_days,
    replay_retention_days = EXCLUDED.replay_retention_days,
    llm_retention_days = EXCLUDED.llm_retention_days,
    status_pages_enabled = EXCLUDED.status_pages_enabled,
    status_page_custom_domain_enabled = EXCLUDED.status_page_custom_domain_enabled,
    session_replay_enabled = EXCLUDED.session_replay_enabled,
    slack_enabled = EXCLUDED.slack_enabled,
    discord_enabled = EXCLUDED.discord_enabled,
    incident_io_enabled = EXCLUDED.incident_io_enabled,
    saml_enabled = EXCLUDED.saml_enabled,
    oidc_enabled = EXCLUDED.oidc_enabled,
    priority_support_enabled = EXCLUDED.priority_support_enabled,
    sla_enabled = EXCLUDED.sla_enabled,
    custom_retention_enabled = EXCLUDED.custom_retention_enabled,
    max_projects = EXCLUDED.max_projects,
    max_systems = EXCLUDED.max_systems,
    monitor_interval_seconds = EXCLUDED.monitor_interval_seconds,
    monthly_price_cents = EXCLUDED.monthly_price_cents,
    yearly_price_cents = EXCLUDED.yearly_price_cents,
    trial_days = EXCLUDED.trial_days,
    payg_enabled = EXCLUDED.payg_enabled,
    payg_rate_micros_per_unit = EXCLUDED.payg_rate_micros_per_unit,
    overage_rate_cents_per_gb = EXCLUDED.overage_rate_cents_per_gb,
    error_overage_rate_cents_per_1k = EXCLUDED.error_overage_rate_cents_per_1k,
    replay_overage_rate_cents_per_gb = EXCLUDED.replay_overage_rate_cents_per_gb,
    llm_overage_rate_cents_per_1k = EXCLUDED.llm_overage_rate_cents_per_1k,
    oncall_per_user_monthly_cents = EXCLUDED.oncall_per_user_monthly_cents,
    oncall_per_user_yearly_cents = EXCLUDED.oncall_per_user_yearly_cents,
    oncall_enabled = EXCLUDED.oncall_enabled,
    max_analytics_sites = EXCLUDED.max_analytics_sites,
    analytics_retention_days = EXCLUDED.analytics_retention_days,
    monthly_analytics_pageview_limit = EXCLUDED.monthly_analytics_pageview_limit,
    analytics_pageview_overage_rate_cents_per_100k = EXCLUDED.analytics_pageview_overage_rate_cents_per_100k,
    monthly_apm_span_limit = EXCLUDED.monthly_apm_span_limit,
    apm_span_overage_rate_cents_per_1m = EXCLUDED.apm_span_overage_rate_cents_per_1m,
    monthly_custom_metric_limit = EXCLUDED.monthly_custom_metric_limit,
    custom_metric_overage_rate_cents_per_100k = EXCLUDED.custom_metric_overage_rate_cents_per_100k,
    max_hosts = EXCLUDED.max_hosts,
    profiling_enabled = EXCLUDED.profiling_enabled,
    network_monitoring_enabled = EXCLUDED.network_monitoring_enabled,
    dbm_enabled = EXCLUDED.dbm_enabled,
    debugger_enabled = EXCLUDED.debugger_enabled,
    k8s_monitoring_enabled = EXCLUDED.k8s_monitoring_enabled,
    data_streams_enabled = EXCLUDED.data_streams_enabled,
    sbom_enabled = EXCLUDED.sbom_enabled,
    synthetics_enabled = EXCLUDED.synthetics_enabled,
    is_current = EXCLUDED.is_current;

-- BUSINESS tier: 1 TB ingestion, unlimited custom metrics, unlimited hosts
INSERT INTO pricing_tier_configs (
    tier_name, version, monthly_unit_limit,
    monthly_error_limit, monthly_transaction_limit, monthly_replay_limit,
    monthly_feedback_limit, monthly_llm_event_limit,
    monthly_gb_limit, retention_days, log_retention_days,
    replay_retention_days, llm_retention_days,
    status_pages_enabled, status_page_custom_domain_enabled,
    session_replay_enabled, slack_enabled, discord_enabled,
    incident_io_enabled, saml_enabled, oidc_enabled,
    priority_support_enabled, sla_enabled, custom_retention_enabled,
    max_projects, max_systems, monitor_interval_seconds,
    monthly_price_cents, yearly_price_cents, trial_days,
    payg_enabled, payg_rate_micros_per_unit,
    overage_rate_cents_per_gb,
    error_overage_rate_cents_per_1k, replay_overage_rate_cents_per_gb,
    llm_overage_rate_cents_per_1k,
    oncall_per_user_monthly_cents, oncall_per_user_yearly_cents, oncall_enabled,
    max_analytics_sites, analytics_retention_days,
    monthly_analytics_pageview_limit, analytics_pageview_overage_rate_cents_per_100k,
    monthly_apm_span_limit, apm_span_overage_rate_cents_per_1m,
    monthly_custom_metric_limit, custom_metric_overage_rate_cents_per_100k,
    max_hosts, profiling_enabled, network_monitoring_enabled,
    dbm_enabled, debugger_enabled, k8s_monitoring_enabled,
    data_streams_enabled, sbom_enabled, synthetics_enabled,
    is_current, created_at
) VALUES (
    'BUSINESS', 3, 9223372036854775807,
    9223372036854775807, 9223372036854775807, 9223372036854775807,
    9223372036854775807, 9223372036854775807,
    1099511627776, 90, 90,
    90, 90,
    true, true,
    true, true, true,
    true, true, true,
    true, true, true,
    NULL, 2147483647, 10,
    19900, 199200, 14,
    true, 400000,
    40,
    0, 0,
    0,
    500, 5000, true,
    NULL, 1825,
    10000000, 1000,
    9223372036854775807, 0,
    9223372036854775807, 50,
    NULL, true, true,
    true, true, true,
    true, true, true,
    true, NOW()
) ON CONFLICT (tier_name, version) DO UPDATE SET
    monthly_unit_limit = EXCLUDED.monthly_unit_limit,
    monthly_error_limit = EXCLUDED.monthly_error_limit,
    monthly_transaction_limit = EXCLUDED.monthly_transaction_limit,
    monthly_replay_limit = EXCLUDED.monthly_replay_limit,
    monthly_feedback_limit = EXCLUDED.monthly_feedback_limit,
    monthly_llm_event_limit = EXCLUDED.monthly_llm_event_limit,
    monthly_gb_limit = EXCLUDED.monthly_gb_limit,
    retention_days = EXCLUDED.retention_days,
    log_retention_days = EXCLUDED.log_retention_days,
    replay_retention_days = EXCLUDED.replay_retention_days,
    llm_retention_days = EXCLUDED.llm_retention_days,
    status_pages_enabled = EXCLUDED.status_pages_enabled,
    status_page_custom_domain_enabled = EXCLUDED.status_page_custom_domain_enabled,
    session_replay_enabled = EXCLUDED.session_replay_enabled,
    slack_enabled = EXCLUDED.slack_enabled,
    discord_enabled = EXCLUDED.discord_enabled,
    incident_io_enabled = EXCLUDED.incident_io_enabled,
    saml_enabled = EXCLUDED.saml_enabled,
    oidc_enabled = EXCLUDED.oidc_enabled,
    priority_support_enabled = EXCLUDED.priority_support_enabled,
    sla_enabled = EXCLUDED.sla_enabled,
    custom_retention_enabled = EXCLUDED.custom_retention_enabled,
    max_projects = EXCLUDED.max_projects,
    max_systems = EXCLUDED.max_systems,
    monitor_interval_seconds = EXCLUDED.monitor_interval_seconds,
    monthly_price_cents = EXCLUDED.monthly_price_cents,
    yearly_price_cents = EXCLUDED.yearly_price_cents,
    trial_days = EXCLUDED.trial_days,
    payg_enabled = EXCLUDED.payg_enabled,
    payg_rate_micros_per_unit = EXCLUDED.payg_rate_micros_per_unit,
    overage_rate_cents_per_gb = EXCLUDED.overage_rate_cents_per_gb,
    error_overage_rate_cents_per_1k = EXCLUDED.error_overage_rate_cents_per_1k,
    replay_overage_rate_cents_per_gb = EXCLUDED.replay_overage_rate_cents_per_gb,
    llm_overage_rate_cents_per_1k = EXCLUDED.llm_overage_rate_cents_per_1k,
    oncall_per_user_monthly_cents = EXCLUDED.oncall_per_user_monthly_cents,
    oncall_per_user_yearly_cents = EXCLUDED.oncall_per_user_yearly_cents,
    oncall_enabled = EXCLUDED.oncall_enabled,
    max_analytics_sites = EXCLUDED.max_analytics_sites,
    analytics_retention_days = EXCLUDED.analytics_retention_days,
    monthly_analytics_pageview_limit = EXCLUDED.monthly_analytics_pageview_limit,
    analytics_pageview_overage_rate_cents_per_100k = EXCLUDED.analytics_pageview_overage_rate_cents_per_100k,
    monthly_apm_span_limit = EXCLUDED.monthly_apm_span_limit,
    apm_span_overage_rate_cents_per_1m = EXCLUDED.apm_span_overage_rate_cents_per_1m,
    monthly_custom_metric_limit = EXCLUDED.monthly_custom_metric_limit,
    custom_metric_overage_rate_cents_per_100k = EXCLUDED.custom_metric_overage_rate_cents_per_100k,
    max_hosts = EXCLUDED.max_hosts,
    profiling_enabled = EXCLUDED.profiling_enabled,
    network_monitoring_enabled = EXCLUDED.network_monitoring_enabled,
    dbm_enabled = EXCLUDED.dbm_enabled,
    debugger_enabled = EXCLUDED.debugger_enabled,
    k8s_monitoring_enabled = EXCLUDED.k8s_monitoring_enabled,
    data_streams_enabled = EXCLUDED.data_streams_enabled,
    sbom_enabled = EXCLUDED.sbom_enabled,
    synthetics_enabled = EXCLUDED.synthetics_enabled,
    is_current = EXCLUDED.is_current;
