-- Convert APM span billing from GB-pooled ingestion to count-based with dedicated limits.

ALTER TABLE org_usage_counters
    ADD COLUMN IF NOT EXISTS used_apm_span_bytes BIGINT NOT NULL DEFAULT 0;

-- Historical rows cannot be split into span vs non-span bytes retroactively.
-- Start existing periods with zero isolated APM span bytes.
UPDATE org_usage_counters
SET used_apm_span_bytes = 0;

-- Replace current standard tier configs with version 4 that enables real APM span limits.
UPDATE pricing_tier_configs
SET is_current = false
WHERE is_current = true
  AND tier_name IN ('FREE', 'PRO', 'TEAM', 'BUSINESS');

WITH latest_standard_tiers AS (
    SELECT DISTINCT ON (tier_name)
        tier_name,
        monthly_unit_limit,
        monthly_error_limit,
        monthly_transaction_limit,
        monthly_replay_limit,
        monthly_feedback_limit,
        monthly_llm_event_limit,
        monthly_gb_limit,
        retention_days,
        replay_retention_days,
        llm_retention_days,
        log_retention_days,
        status_pages_enabled,
        status_page_custom_domain_enabled,
        session_replay_enabled,
        slack_enabled,
        discord_enabled,
        incident_io_enabled,
        saml_enabled,
        oidc_enabled,
        priority_support_enabled,
        sla_enabled,
        custom_retention_enabled,
        max_projects,
        max_systems,
        monitor_interval_seconds,
        monthly_price_cents,
        yearly_price_cents,
        trial_days,
        payg_enabled,
        payg_rate_micros_per_unit,
        overage_rate_cents_per_gb,
        error_overage_rate_cents_per_1k,
        replay_overage_rate_cents_per_gb,
        llm_overage_rate_cents_per_1k,
        oncall_per_user_monthly_cents,
        oncall_per_user_yearly_cents,
        oncall_enabled,
        max_analytics_sites,
        analytics_retention_days,
        monthly_analytics_pageview_limit,
        analytics_pageview_overage_rate_cents_per_100k,
        monthly_custom_metric_limit,
        custom_metric_overage_rate_cents_per_100k,
        max_hosts,
        profiling_enabled,
        network_monitoring_enabled,
        dbm_enabled,
        debugger_enabled,
        k8s_monitoring_enabled,
        data_streams_enabled,
        sbom_enabled,
        synthetics_enabled,
        stripe_base_price_id,
        stripe_overage_price_id,
        stripe_yearly_base_price_id,
        stripe_yearly_overage_price_id,
        stripe_oncall_price_id,
        stripe_oncall_yearly_price_id
    FROM pricing_tier_configs
    WHERE tier_name IN ('FREE', 'PRO', 'TEAM', 'BUSINESS')
    ORDER BY tier_name, version DESC
)
INSERT INTO pricing_tier_configs (
    tier_name,
    version,
    monthly_unit_limit,
    monthly_error_limit,
    monthly_transaction_limit,
    monthly_replay_limit,
    monthly_feedback_limit,
    monthly_llm_event_limit,
    monthly_gb_limit,
    retention_days,
    replay_retention_days,
    llm_retention_days,
    log_retention_days,
    status_pages_enabled,
    status_page_custom_domain_enabled,
    session_replay_enabled,
    slack_enabled,
    discord_enabled,
    incident_io_enabled,
    saml_enabled,
    oidc_enabled,
    priority_support_enabled,
    sla_enabled,
    custom_retention_enabled,
    max_projects,
    max_systems,
    monitor_interval_seconds,
    monthly_price_cents,
    yearly_price_cents,
    trial_days,
    payg_enabled,
    payg_rate_micros_per_unit,
    overage_rate_cents_per_gb,
    error_overage_rate_cents_per_1k,
    replay_overage_rate_cents_per_gb,
    llm_overage_rate_cents_per_1k,
    oncall_per_user_monthly_cents,
    oncall_per_user_yearly_cents,
    oncall_enabled,
    max_analytics_sites,
    analytics_retention_days,
    monthly_analytics_pageview_limit,
    analytics_pageview_overage_rate_cents_per_100k,
    monthly_apm_span_limit,
    apm_span_overage_rate_cents_per_1m,
    monthly_custom_metric_limit,
    custom_metric_overage_rate_cents_per_100k,
    max_hosts,
    profiling_enabled,
    network_monitoring_enabled,
    dbm_enabled,
    debugger_enabled,
    k8s_monitoring_enabled,
    data_streams_enabled,
    sbom_enabled,
    synthetics_enabled,
    stripe_base_price_id,
    stripe_overage_price_id,
    stripe_yearly_base_price_id,
    stripe_yearly_overage_price_id,
    stripe_oncall_price_id,
    stripe_oncall_yearly_price_id,
    is_current,
    created_at
)
SELECT
    tier_name,
    4,
    monthly_unit_limit,
    monthly_error_limit,
    monthly_transaction_limit,
    monthly_replay_limit,
    monthly_feedback_limit,
    monthly_llm_event_limit,
    monthly_gb_limit,
    retention_days,
    replay_retention_days,
    llm_retention_days,
    log_retention_days,
    status_pages_enabled,
    status_page_custom_domain_enabled,
    session_replay_enabled,
    slack_enabled,
    discord_enabled,
    incident_io_enabled,
    saml_enabled,
    oidc_enabled,
    priority_support_enabled,
    sla_enabled,
    custom_retention_enabled,
    max_projects,
    max_systems,
    monitor_interval_seconds,
    monthly_price_cents,
    yearly_price_cents,
    trial_days,
    payg_enabled,
    payg_rate_micros_per_unit,
    overage_rate_cents_per_gb,
    error_overage_rate_cents_per_1k,
    replay_overage_rate_cents_per_gb,
    llm_overage_rate_cents_per_1k,
    oncall_per_user_monthly_cents,
    oncall_per_user_yearly_cents,
    oncall_enabled,
    max_analytics_sites,
    analytics_retention_days,
    monthly_analytics_pageview_limit,
    analytics_pageview_overage_rate_cents_per_100k,
    CASE tier_name
        WHEN 'FREE' THEN 500000
        WHEN 'PRO' THEN 10000000
        WHEN 'TEAM' THEN 50000000
        WHEN 'BUSINESS' THEN 200000000
        ELSE 0
    END,
    CASE tier_name
        WHEN 'FREE' THEN 0
        ELSE 30
    END,
    monthly_custom_metric_limit,
    custom_metric_overage_rate_cents_per_100k,
    max_hosts,
    profiling_enabled,
    network_monitoring_enabled,
    dbm_enabled,
    debugger_enabled,
    k8s_monitoring_enabled,
    data_streams_enabled,
    sbom_enabled,
    synthetics_enabled,
    stripe_base_price_id,
    stripe_overage_price_id,
    stripe_yearly_base_price_id,
    stripe_yearly_overage_price_id,
    stripe_oncall_price_id,
    stripe_oncall_yearly_price_id,
    true,
    NOW()
FROM latest_standard_tiers
ON CONFLICT (tier_name, version) DO UPDATE SET
    monthly_apm_span_limit = EXCLUDED.monthly_apm_span_limit,
    apm_span_overage_rate_cents_per_1m = EXCLUDED.apm_span_overage_rate_cents_per_1m,
    is_current = EXCLUDED.is_current;
