#!/usr/bin/env bash
set -euo pipefail

# Blue/green deployment script. Run from repo root (e.g. /opt/moneat).
# Usage: ./deploy/scripts/deploy.sh <IMAGE_TAG>
# Requires: .env, external volumes created, docker compose.

IMAGE_TAG="${1:?Usage: $0 <IMAGE_TAG>}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
COMPOSE_FILE="$REPO_ROOT/docker-compose.prod.yml"
ACTIVE_SLOT_FILE="$REPO_ROOT/active-slot"
NGINX_CONF_DIR="$REPO_ROOT/deploy/nginx/conf.d"
UPSTREAM_CONF="$NGINX_CONF_DIR/upstream.conf"

cd "$REPO_ROOT"

if [[ ! -f .env ]]; then
  echo "ERROR: .env not found in $REPO_ROOT"
  exit 1
fi

# Load env for compose
set -a
source .env
set +a

export IMAGE_TAG
export BACKEND_IMAGE="${BACKEND_IMAGE:-ghcr.io/moneat/backend}"
export DASHBOARD_IMAGE="${DASHBOARD_IMAGE:-ghcr.io/moneat/dashboard}"

# 1. Read current active slot
ACTIVE="blue"
if [[ -f "$ACTIVE_SLOT_FILE" ]]; then
  ACTIVE="$(cat "$ACTIVE_SLOT_FILE" | tr -d '[:space:]')"
fi
[[ "$ACTIVE" == "blue" || "$ACTIVE" == "green" ]] || ACTIVE="blue"

# 2. Inactive slot is the one we will deploy to
INACTIVE="green"
[[ "$ACTIVE" == "green" ]] && INACTIVE="blue"

echo "Active slot: $ACTIVE -> deploying to slot: $INACTIVE (tag: $IMAGE_TAG)"

# 3. Ensure infrastructure is running (do not touch database containers)
docker compose -f "$COMPOSE_FILE" up -d nginx certbot postgres clickhouse redis 2>/dev/null || true

# 3a. Wait for databases to be healthy (up to 60s)
echo "Waiting for databases to be healthy..."
for i in {1..30}; do
  POSTGRES_HEALTHY=$(docker inspect moneat-postgres --format='{{.State.Health.Status}}' 2>/dev/null || echo "starting")
  CLICKHOUSE_HEALTHY=$(docker inspect moneat-clickhouse --format='{{.State.Health.Status}}' 2>/dev/null || echo "starting")
  REDIS_HEALTHY=$(docker inspect moneat-redis --format='{{.State.Health.Status}}' 2>/dev/null || echo "starting")
  
  if [[ "$POSTGRES_HEALTHY" == "healthy" && "$CLICKHOUSE_HEALTHY" == "healthy" && "$REDIS_HEALTHY" == "healthy" ]]; then
    echo "All databases healthy"
    break
  fi
  
  if [[ $i -eq 30 ]]; then
    echo "ERROR: Databases failed to become healthy after 60s"
    echo "  Postgres: $POSTGRES_HEALTHY"
    echo "  ClickHouse: $CLICKHOUSE_HEALTHY"
    echo "  Redis: $REDIS_HEALTHY"
    exit 1
  fi
  
  echo "  Waiting... (Postgres: $POSTGRES_HEALTHY, ClickHouse: $CLICKHOUSE_HEALTHY, Redis: $REDIS_HEALTHY)"
  sleep 2
done

# 4. Pull new images
docker compose -f "$COMPOSE_FILE" pull backend-$INACTIVE dashboard-$INACTIVE

# 5. Start inactive slot
docker compose -f "$COMPOSE_FILE" up -d backend-$INACTIVE dashboard-$INACTIVE

# 6. Wait for backend health (up to 60s)
echo "Waiting for backend-$INACTIVE /health..."
for i in {1..30}; do
  # Check from backend container itself (avoids nginx restart issues)
  if docker exec moneat-backend-$INACTIVE wget --spider --quiet --tries=1 --timeout=2 "http://localhost:8080/health" 2>&1; then
    echo "Health OK"
    break
  fi
  if [[ $i -eq 30 ]]; then
    echo "ERROR: backend-$INACTIVE health check failed after 60s"
    echo "Checking backend logs:"
    docker logs moneat-backend-$INACTIVE --tail 50
    docker compose -f "$COMPOSE_FILE" stop backend-$INACTIVE dashboard-$INACTIVE
    exit 1
  fi
  sleep 2
done

# 7. Generate upstream.conf pointing to the new slot
TEMP_UPSTREAM=$(mktemp)
cat > "$TEMP_UPSTREAM" << EOF
# Generated by deploy script - do not edit by hand.
upstream backend_upstream {
    server backend-$INACTIVE:8080;
}
upstream dashboard_upstream {
    server dashboard-$INACTIVE:80;
}
EOF
mv "$TEMP_UPSTREAM" "$UPSTREAM_CONF" || {
  # If move fails due to permissions, try with sudo
  sudo mv "$TEMP_UPSTREAM" "$UPSTREAM_CONF"
  sudo chown deploy:deploy "$UPSTREAM_CONF" 2>/dev/null || true
}

# 8. Reload nginx
docker exec moneat-nginx nginx -s reload

# 9. Stop old slot
docker compose -f "$COMPOSE_FILE" stop backend-$ACTIVE dashboard-$ACTIVE

# 10. Record new active slot
echo -n "$INACTIVE" > "$ACTIVE_SLOT_FILE"

# 11. Safe prune: images only, never volumes
docker image prune -f --filter "until=24h" || true

# 12. Assert database volumes still exist
for vol in moneat_postgres_data moneat_clickhouse_data; do
  if ! docker volume inspect "$vol" &>/dev/null; then
    echo "ERROR: Volume $vol is missing. Never run 'docker system prune --volumes' or 'docker volume prune' on production."
    exit 1
  fi
done
echo "Volume check OK"

echo "Deploy complete. Active slot: $INACTIVE"
