#!/usr/bin/env bash
set -euo pipefail

# Blue/green deployment script. Run from repo root (e.g. /opt/moneat).
# Usage: ./deploy/scripts/deploy.sh <IMAGE_TAG>
# Requires: .env.prod, external volumes created, docker compose.

IMAGE_TAG="${1:?Usage: $0 <IMAGE_TAG>}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
COMPOSE_FILE="$REPO_ROOT/docker-compose.prod.yml"
ACTIVE_SLOT_FILE="$REPO_ROOT/active-slot"
NGINX_CONF_DIR="$REPO_ROOT/deploy/nginx/conf.d"
UPSTREAM_CONF="$NGINX_CONF_DIR/upstream.conf"

cd "$REPO_ROOT"

if [[ ! -f .env.prod ]]; then
  echo "ERROR: .env.prod not found in $REPO_ROOT"
  exit 1
fi

# Load env for compose
set -a
source .env.prod
set +a

export IMAGE_TAG
export BACKEND_IMAGE="${BACKEND_IMAGE:-ghcr.io/moneat/backend}"
export DASHBOARD_IMAGE="${DASHBOARD_IMAGE:-ghcr.io/moneat/dashboard}"

# 1. Read current active slot
ACTIVE="blue"
if [[ -f "$ACTIVE_SLOT_FILE" ]]; then
  ACTIVE="$(cat "$ACTIVE_SLOT_FILE" | tr -d '[:space:]')"
fi
[[ "$ACTIVE" == "blue" || "$ACTIVE" == "green" ]] || ACTIVE="blue"

# 2. Inactive slot is the one we will deploy to
INACTIVE="green"
[[ "$ACTIVE" == "green" ]] && INACTIVE="blue"

echo "Active slot: $ACTIVE -> deploying to slot: $INACTIVE (tag: $IMAGE_TAG)"

# 3. Ensure infrastructure is running (do not touch database containers)
docker compose -f "$COMPOSE_FILE" up -d nginx certbot postgres clickhouse redis 2>/dev/null || true

# 4. Pull new images
docker compose -f "$COMPOSE_FILE" pull backend-$INACTIVE dashboard-$INACTIVE

# 5. Start inactive slot
docker compose -f "$COMPOSE_FILE" up -d backend-$INACTIVE dashboard-$INACTIVE

# 6. Wait for backend health (up to 60s)
echo "Waiting for backend-$INACTIVE /health..."
for i in {1..30}; do
  if docker exec moneat-nginx wget -qO- "http://backend-$INACTIVE:8080/health" 2>/dev/null | grep -q '"status":"ok"'; then
    echo "Health OK"
    break
  fi
  if [[ $i -eq 30 ]]; then
    echo "ERROR: backend-$INACTIVE health check failed after 60s"
    docker compose -f "$COMPOSE_FILE" stop backend-$INACTIVE dashboard-$INACTIVE
    exit 1
  fi
  sleep 2
done

# 7. Generate upstream.conf pointing to the new slot
cat > "$UPSTREAM_CONF" << EOF
# Generated by deploy script - do not edit by hand.
upstream backend_upstream {
    server backend-$INACTIVE:8080;
}
upstream dashboard_upstream {
    server dashboard-$INACTIVE:80;
}
EOF

# 8. Reload nginx
docker exec moneat-nginx nginx -s reload

# 9. Stop old slot
docker compose -f "$COMPOSE_FILE" stop backend-$ACTIVE dashboard-$ACTIVE

# 10. Record new active slot
echo -n "$INACTIVE" > "$ACTIVE_SLOT_FILE"

# 11. Safe prune: images only, never volumes
docker image prune -f --filter "until=24h" || true

# 12. Assert database volumes still exist
for vol in moneat_postgres_data moneat_clickhouse_data; do
  if ! docker volume inspect "$vol" &>/dev/null; then
    echo "ERROR: Volume $vol is missing. Never run 'docker system prune --volumes' or 'docker volume prune' on production."
    exit 1
  fi
done
echo "Volume check OK"

echo "Deploy complete. Active slot: $INACTIVE"
