CREATE TABLE IF NOT EXISTS app_subscription_events (
    event_id UUID DEFAULT generateUUIDv4(),
    organization_id UInt64,
    project_id Nullable(UInt64),
    installation_id UInt64,
    installation_resource_id UUID,
    raw_event_id UInt64,
    provider LowCardinality(String),
    provider_api_version Nullable(String),
    provider_event_id String,
    received_at DateTime64(3, 'UTC'),
    event_timestamp DateTime64(3, 'UTC'),
    event_timestamp_ms Int64,
    event_type LowCardinality(String),
    event_category Nullable(String),
    revenuecat_project_id Nullable(String),
    revenuecat_app_id Nullable(String),
    store Nullable(String),
    environment Nullable(String),
    app_user_id Nullable(String),
    original_app_user_id Nullable(String),
    aliases Array(String),
    transferred_from Array(String),
    transferred_to Array(String),
    customer_lookup_keys Array(String),
    currency Nullable(String),
    price_usd Nullable(Float64),
    price_in_purchased_currency Nullable(Float64),
    tax_percentage Nullable(Float64),
    commission_percentage Nullable(Float64),
    proceeds_estimate_usd Nullable(Float64),
    country_code Nullable(String),
    is_family_share UInt8,
    store_product_id Nullable(String),
    new_store_product_id Nullable(String),
    entitlement_ids Array(String),
    period_type Nullable(String),
    purchased_at Nullable(DateTime64(3, 'UTC')),
    expiration_at Nullable(DateTime64(3, 'UTC')),
    grace_period_expiration_at Nullable(DateTime64(3, 'UTC')),
    auto_resume_at Nullable(DateTime64(3, 'UTC')),
    transaction_id Nullable(String),
    original_transaction_id Nullable(String),
    cancel_reason Nullable(String),
    expiration_reason Nullable(String),
    presented_offering_id Nullable(String),
    offer_code Nullable(String),
    is_trial_conversion UInt8,
    renewal_number Nullable(Int64),
    inserted_at DateTime64(3, 'UTC') DEFAULT now64(3)
) ENGINE = MergeTree()
PARTITION BY toYYYYMM(received_at)
ORDER BY (organization_id, installation_id, provider_event_id)
TTL received_at + INTERVAL 730 DAY
SETTINGS non_replicated_deduplication_window = 1000;
